table Sheet3
	lineageTag: 6a46a42f-a921-47e6-86d5-c50336256de9

	column Column1
		dataType: string
		lineageTag: 4de51974-2675-46e0-b40a-1d34bce221f9
		summarizeBy: none
		sourceColumn: Column1

		annotation SummarizationSetBy = Automatic

	column Column2
		dataType: string
		lineageTag: c6792cea-606e-449d-9b02-beaeceedcd84
		summarizeBy: none
		sourceColumn: Column2

		annotation SummarizationSetBy = Automatic

	partition Sheet3 = m
		mode: import
		source =
				let
				  Source = Excel.Workbook(File.Contents("D:\Coding_Projects\PowerBI\uber_dataset.xlsx"), null, true),
				  #"Navigation 1" = Source{[Item = "Sheet3", Kind = "Sheet"]}[Data],
				  #"Changed column type" = Table.TransformColumnTypes(#"Navigation 1", {{"Column1", type text}, {"Column2", type text}}, "en-US")
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

